### ISSUE TITLE
Add license to pythonscripts

### ISSUE THREAD

**Issue by eb-oss** [MaartenSmeets/pythonscripts#1]
Hi Maarten, I work for the Linux Foundation, and we would like to adapt your nexus2/cleanup.py script to be part of our lftools (https://gerrit.linuxfoundation.org/infra/#/admin/projects/releng/lftools). In order to do this, I was hoping you might be able to add an EPL-compatible license to this repo, or at least that file (Eclipse has a list of acceptable licenses here: http://www.eclipse.org/legal/licenses.php). Alternatively, if you would be interested, we'd also be happy to have your code contributed directly to lftools! Thanks for your time.

**Comment by MaartenSmeets** [comment]
Hi Eric,

Glad to hear you want to add my code! I've added the MIT license to the repository root.

With kind regards,
Maarten
